services:
  swagger-editor:
    image: docker.swagger.io/swaggerapi/swagger-editor
    container_name: swagger-editor
    ports:
      - "8080:8080"
    environment:
      SWAGGER_FILE: /tmp/openapi.yaml
    volumes:
      - ./openapi.yaml:/tmp/openapi.yaml